"""Stable metric definition and delivery matrix."""

from __future__ import annotations

from typing import Any

FORMULA_PARTS = {
    "MET-001": ("explicit accepted outcomes", "not applicable"),
    "MET-002": ("union duration of valid half-open intervals", "not applicable"),
    "MET-003": ("passed first expected gates", "all expected gate starts"),
    "MET-004": ("work items classified as reworked", "classified work items"),
    "MET-005": ("explicit measured attention seconds", "not applicable"),
    "MET-006": ("explicit transferred context bytes", "not applicable"),
    "MET-007": ("complete provider-reported token counts", "not applicable"),
    "MET-008": ("latest valid sample per account alias", "registered samples"),
    "MET-009": ("attempts with complete usage", "observed attempts"),
    "MET-010": ("delivered terminal requests", "terminal delivery attempts"),
    "MET-011": ("equivalent attempts without evidence delta", "observed attempts"),
}

DELIVERY_COVERAGE = {
    "MET-001": {
        "calculated": [
            "explicit_accepted_outcome_count",
            "baseline_and_current_scope_progress",
            "scope_state_distribution",
            "scope_growth_and_change_reasons",
            "module_progress",
            "reopened_outcome_handling",
            "work_item_state_distribution",
            "open_item_age_percentiles",
        ],
        "evidence_views": ["work_item_status", "scope_revision", "criteria_refs"],
        "external": ["project_acceptance_authority", "weighted_progress_policy"],
    },
    "MET-002": {
        "calculated": [
            "elapsed_interval_union",
            "root_execution_sum",
            "nested_execution_breakdown",
            "empirical_p50_p80_equivalent_effort_forecast",
            "attempt_duration_percentiles",
        ],
        "evidence_views": ["wait_reason", "queue_state", "handoff_state"],
        "external": ["dependency_graph", "comparable_forecast_cohort"],
    },
    "MET-003": {
        "calculated": ["first_expected_gate_pass_rate"],
        "evidence_views": ["verification_role", "attempt_status", "failure_class"],
        "external": ["test_reporter_detail", "coverage_authority", "flaky_proof"],
    },
    "MET-004": {
        "calculated": ["explicit_rework_rate"],
        "evidence_views": ["finding_severity", "detection_stage", "disposition"],
        "external": ["post_acceptance_followup", "incident_exposure"],
    },
    "MET-005": {
        "calculated": ["explicit_human_attention_seconds"],
        "evidence_views": ["handoff", "owner_intervention", "worker_role"],
        "external": ["voluntary_owner_assessment", "host_chat_usage"],
    },
    "MET-006": {
        "calculated": ["explicit_context_bytes"],
        "evidence_views": ["document_ref", "context_gap", "reuse_decision"],
        "external": ["documentation_adapter", "direct_context_token_counter"],
    },
    "MET-007": {
        "calculated": ["provider_tokens", "conserved_cost_buckets"],
        "evidence_views": ["resource_sample", "cache_state", "contention"],
        "external": ["host_resource_sampler", "billing_adapter", "price_policy"],
    },
    "MET-008": {
        "calculated": [
            "latest_quota_sample_per_account",
            "latest_quota_sample_per_bucket_window",
            "safe_quota_interval_deltas",
            "reset_discontinuity_detection",
        ],
        "evidence_views": ["reset_at", "rounding", "window_identity"],
        "external": ["provider_quota_collector", "capacity_forecast_policy"],
    },
    "MET-009": {
        "calculated": ["complete_usage_coverage"],
        "evidence_views": ["measurement_status", "account_alias"],
        "external": ["direct_account_attribution", "shared_allocation_policy"],
    },
    "MET-010": {
        "calculated": ["terminal_delivery_success_rate"],
        "evidence_views": ["delivery_status", "manual_acknowledgement"],
        "external": ["independent_incident_confirmation", "retention_gap_source"],
    },
    "MET-011": {
        "calculated": ["equivalent_attempts_without_evidence_delta"],
        "evidence_views": ["architecture_classification", "product_feedback_ref"],
        "external": ["deployment_identity", "adoption_and_incident_contract"],
    },
}


def _definition(
    metric_id: str,
    name: str,
    family: str,
    unit: str,
    question: str,
    decision: str,
    record_types: list[str],
    aggregation: str,
    limitations: str,
) -> dict[str, Any]:
    numerator, denominator = FORMULA_PARTS[metric_id]
    delivery = DELIVERY_COVERAGE[metric_id]
    return {
        "metric_id": metric_id,
        "definition_version": 1,
        "implementation_status": "calculation_tested",
        "producer_status": "explicit_source_required",
        "name": name,
        "family": family,
        "question": question,
        "decision": decision,
        "unit": unit,
        "sources": record_types,
        "object_scope": "filtered report cohort",
        "numerator": numerator,
        "denominator": denominator,
        "interval_rules": "half-open intervals; nested work is not double counted",
        "aggregation": aggregation,
        "exclusions": "malformed, out-of-scope and explicitly unavailable records",
        "cutoff": "report evaluation_time",
        "classification_provenance": "observation source and generation digest",
        "coverage_requirements": "report known, unknown and partial separately",
        "limitations": limitations,
        "guardrails": "advisory only; never an acceptance or quota authority",
        "comparison_dimensions": ["generation", "cohort", "policy"],
        "visibility": "public aggregate; evidence pointers remain local",
        "calculated_fields": delivery["calculated"],
        "evidence_view_fields": delivery["evidence_views"],
        "external_integration_fields": delivery["external"],
    }


METRIC_DEFINITIONS = (
    _definition(
        "MET-001",
        "Accepted outcomes",
        "outcomes",
        "count",
        "How many work items have explicit acceptance evidence?",
        "Assess delivered scope without treating process exit as acceptance.",
        ["acceptance"],
        "count accepted records",
        "Requires an explicit acceptance producer.",
    ),
    _definition(
        "MET-002",
        "Active execution time",
        "flow",
        "seconds",
        "How much non-overlapping execution time occurred?",
        "Separate active work from wall-clock waiting.",
        ["execution_attempt"],
        "union of half-open execution intervals",
        "Missing interval boundaries reduce coverage.",
    ),
    _definition(
        "MET-003",
        "First-gate pass rate",
        "verification",
        "ratio",
        "How often did the first expected gate pass?",
        "Target repair effort without weakening final verification.",
        ["execution_attempt"],
        "passed / all expected first gates",
        "Pending and cancelled expected gates remain in the denominator.",
    ),
    _definition(
        "MET-004",
        "Rework rate",
        "quality",
        "ratio",
        "How often did accepted work require corrective rework?",
        "Identify unstable implementation or review boundaries.",
        ["work_item"],
        "reworked / classified work items",
        "Rework classification is project supplied.",
    ),
    _definition(
        "MET-005",
        "Human attention",
        "collaboration",
        "seconds",
        "How much measured human attention did the workflow require?",
        "Reduce coordination burden without claiming human time from wall time.",
        ["work_item"],
        "sum explicit human_attention_seconds",
        "Unknown unless explicitly measured.",
    ),
    _definition(
        "MET-006",
        "Context volume",
        "knowledge",
        "bytes",
        "How much recorded context was transferred?",
        "Compare bounded summaries with repeated full-log reads.",
        ["work_item", "execution_attempt"],
        "sum explicit context_bytes",
        "Bytes are not converted to tokens.",
    ),
    _definition(
        "MET-007",
        "Provider-reported tokens",
        "resources",
        "tokens",
        "How many tokens did provider usage events explicitly report?",
        "Compare profiles only when source coverage is sufficient.",
        ["execution_attempt"],
        "sum provider-reported total_tokens",
        "No inference from bytes, pricing or truncated logs.",
    ),
    _definition(
        "MET-008",
        "Quota remaining",
        "capacity",
        "percentage_points",
        "What is the latest explicitly reported quota remaining?",
        "Avoid dispatch only when account scope and freshness are known.",
        ["quota_sample"],
        "latest sample per account alias",
        "A point-in-time sample is not a future quota guarantee.",
    ),
    _definition(
        "MET-009",
        "Usage coverage",
        "quota_attribution",
        "ratio",
        "What fraction of attempts have real provider usage data?",
        "Prevent optimization decisions based on zeros that mean unknown.",
        ["execution_attempt"],
        "known usage attempts / all attempts",
        "Shared-account attribution remains explicit and may be partial.",
    ),
    _definition(
        "MET-010",
        "Delivery success rate",
        "workflow_reliability",
        "ratio",
        "How often did requested completion delivery succeed?",
        "Find watcher and host-channel reliability problems.",
        ["delivery"],
        "delivered / terminal delivery attempts",
        "Queued and revoked deliveries are reported separately.",
    ),
    _definition(
        "MET-011",
        "Equivalent repetition",
        "architecture_feedback",
        "count",
        "How many equivalent attempts added no useful evidence?",
        "Recommend diagnosis before another identical action.",
        ["execution_attempt"],
        "count repeated purpose/input records without evidence delta",
        "Changed inputs or useful evidence are not loops.",
    ),
)

METRICS_BY_ID = {item["metric_id"]: item for item in METRIC_DEFINITIONS}
